---
srcBase: /home/sean
dstBase: /home/sean
dotfiles_url: https://github.com/endorsystems/dotfiles.git
serif_font: Noto Serif
sans_serif_font: Noto Sans
monospace_font: Noto Mono
required_packages:
  - i3-gaps
  - rofi
  - dunst
  - cups
  - cups-pdf
  - avahi
  - nss-mdns
  - docker
  - docker-compose
  - vagrant
  - virtualbox
  - virtualbox-guest-utils
  - minikube
  - alsa
  - pulseaudio
  - pulseaudio-alsa
  - pulseaudio-bluetooth
  - pulseaudio-equalizer
  - pulsemixer
  - playerctl
  - samba
  - ttf-dejavu
  - ttf-liberation 
  - noto-fonts
  - neofetch
  - caprine
  - picom
  - tmux
  - grim
  - libreoffice-fresh
  - code
  - network-manager-applet
  - nm-connection-editor
  - sane
  - thunar

required_aur:
  - polybar

enabled_services:
  - cups.service
  - avahi-daemon.service
  
  

