---
dots_url: https://github.com/endorsystems/dotfiles.git
serif_font: Noto Serif
sans_serif_font: Noto Sans
monospace_font: Noto Mono
required_packages:
  - i3-gaps
  - rofi
  - dunst
  - cups
  - cups-pdf
  - avahi
  - nss-mdns
  - docker
  - docker-compose
  - vagrant
  - virtualbox
  - virtualbox-guest-utils
  - minikube
  - alsa
  - pulseaudio
  - pulseaudio-alsa
  - pulseaudio-bluetooth
  - pulseaudio-equalizer
  - bluez-utils
  - pulsemixer
  - playerctl
  - samba
  - ttf-dejavu
  - ttf-liberation 
  - noto-fonts
  - neofetch
  - caprine
  - picom
  - tmux
  - grim
  - libreoffice-fresh
  - code
  - network-manager-applet
  - nm-connection-editor
  - sane
  - thunar
  - xorg
  - xorg-xinit
  - feh
  - polybar
  - i3lock-color
  - betterlockscreen
required_aur:
remove_packages:
enabled_services:
  - cups.service
  - avahi-daemon.service
  - bluetooth.service
dots_links:
  - { src: "xfiles/.xinitrc", dst: ".xinitrc"}
  - { src: "bash/.bash_profile", dst: ".bash_profile" }
  # - { src: "bash/.bashrc", dst: ".bashrc" }
  # - { src: "dunst/dunst", dst: ".config/dunst" }
  # - { src: "rofi/config", dst: ".config/rofi/config" }
  # - { src: "picom/config", dst: ".config/picom.conf" }
  # - { src: "i3/i3_config", dst: ".config/i3/config" }
  # - { src: "i3/i3_colors", dst: ".config/i3/colors"}
  # - { src: "polybar/polybar_config", dst: ".config/polybar/config" }

