---
dots_url: https://github.com/shelmus/dotfiles.git
required_packages:
  - cups
  - cups-pdf
  - avahi
  - nss-mdns
  - alacritty
  - docker
  - docker-compose
  - bluez
  - bluez-utils
  - pipewire
  - pipewire-pulse
  - pipewire-alsa
  - pipewire-jack
  - pipewire-docs
  - samba
  - neofetch
  - tmux
  - sane
  - feh
  - unzip
  - ttf-dejavu
  - ttf-liberation
  - noto-fonts
  - noto-fonts-extra
  - noto-fonts-emoji
  - ttf-fira-mono
  - ttf-fira-sans
  - ttf-fira-code
  - ttf-nerd-fonts-symbols
  - htop
  - xdg-desktop-portal-wlr
  - xdg-user-dirs
# gui items
  - sway
  - swayidle
  - swaylock
  - waybar
  - wofi
  - mako
  - code
  - imagemagick
  - papirus-icon-theme
  - nvidia
  - remmina
  - freerdp
  - wofi-wifi-menu-git
  - fontconfig
  - lxappearance
  - zathura
  - libva-intel-driver
  - libva-vdpau-driver
  - libreoffice-fresh
  - google-chrome
  - yad
  - gnome-calculator
# xwayland
  - xorg-xwayland
# workrelated
  - teams
  # - rocketchat-desktop
  - openfortivpn
enabled_services:
  - cups.service
  - avahi-daemon.service
  - bluetooth.service
dots_links:
  - { src: "mako", dst: ".config/mako" }
  - { src: "waybar", dst: ".config/waybar" }
  - { src: "sway", dst: ".config/sway" }
  - { src: "wofi", dst: ".config/wofi"}
  - { src: "alacritty", dst: ".config/alacritty" }
  - { src: "backgrounds", dst: ".backgrounds" }
  - { src: "fonts", dst: ".fonts" }
  - { src: "scripts", dst: ".scripts" }
  - { src: "zsh/.zprofile", dst: ".zprofile" }
  - { src: "zsh/.zshrc", dst: ".zshrc" }
  - { src: "zsh/.zsh", dst: ".zsh" }
  - { src: "zsh/.zshenv", dst: ".zshenv" }
  - { src: "tmux/.tmux.conf", dst: ".tmux.conf" }
git_requirements:
  - { repo: "https://github.com/ohmyzsh/ohmyzsh.git", dst: "{{ ansible_user_dir }}/.oh-my-zsh"}
  - { repo: "https://github.com/denysdovhan/spaceship-prompt.git", dst: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/spaceship-prompt"}
  - { repo: "https://github.com/dracula/gtk.git", dst: "{{ ansible_user_dir }}/.themes/Dracula"}