---
- hosts: localhost
  become: yes

  roles:
    - kewlfft.aur

  vars_files:
    - vars/main.yml

  tasks:
  - name: Install all required packages
    community.general.pacman:
        name: '{{ item }}'
        state: present
    with_items: '{{ required_packages }}'

  - name: Install AUR packages
    aur:
        name: '{{ item }}'
        state: present
    with_items: '{{ required_aur }}'
    become: no

  - name: Setup nsswitch.conf
    copy:
        src: files/nsswitch.conf
        dest: /etc/nsswitch.conf
        backup: yes
    notify: restart_avahi
    
  - name: Setup fonts
    blockinfile:
        path: /etc/fonts/local.conf
        block: |
            <?xml version="1.0"?>
            <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
            <fontconfig>
                <match>
                    <edit mode="prepend" name="family"><string>{{ sans_serif_font }}</string></edit>
                </match>
                <match target="pattern">
                    <test qual="any" name="family"><string>serif</string></test>
                    <edit name="family" mode="assign" binding="same"><string>{{ serif_font }}</string></edit>
                </match>
                <match target="pattern">
                    <test qual="any" name="family"><string>sans-serif</string></test>
                    <edit name="family" mode="assign" binding="same"><string>{{ sans_serif_font }}</string></edit>
                </match>
                <match target="pattern">
                    <test qual="any" name="family"><string>monospace</string></test>
                    <edit name="family" mode="assign" binding="same"><string>{{ monospace_font }}</string></edit>
                </match>
            </fontconfig>
        create: yes

  - name: Create bitmap symlinks
    file:
        src: "/etc/fonts/conf.avail/{{ item }}"
        dest: "/etc/fonts/conf.d/{{ item }}"
        state: link
    with_items:
        - 70-no-bitmaps.conf
        - 10-sub-pixel-rgb.conf
        - 11-lcdfilter-default.conf

  - name: Enable freetype properties
    replace:
      path: /etc/profile.d/freetype2.sh
      regexp: '^#(.*FREETYPE_PROPERTIES.*)'
      replace: '\1'

  - name: Enable systemd stuff
    systemd:
        name: '{{ item }}'
        state: started
        enabled: yes
    with_items: '{{ enabled_services }}'

  - name: User mods
    user:
        name: sean
        groups: docker
        append: yes

  - name: Download dotfiles
    git:
        repo: '{{ dotfiles_url }}'
        dest: "{{ srcBase }}/dotfiles"
        update: yes
    become: no

  - name: Install dotfiles
    file:
        src: "{{ srcBase }}/dotfiles/{{ item.src }}"
        dest: "{{ dstBase }}/{{ item.dst }}"
        state: link
        force: yes
    with_items: '{{ dotfile_locations }}'
        # - { src: "bash/.bash_profile", dst: ".bash_profile" }
        # - { src: "bash/.bashrc", dst: ".bashrc" }
        # - { src: "dunst/dunst", dst: ".config/dunst" }
        # - { src: "rofi/config", dst: ".config/rofi/config" }
        # - { src: "picom/config", dst: ".config/picom.conf" }
        # - { src: "i3/i3_config", dst: ".config/i3/config" }
        # - { src: "i3/i3_colors", dst: ".config/i3/colors"}
        # - { src: "polybar/polybar_config", dst: ".config/polybar/config" }

# HANDLERS
  handlers:
    - name: restart_avahi
      ansible.builtin.service:
        name: avahi-daemon
        state: restarted