---
- hosts: localhost
  become: no

  roles:
    - kewlfft.aur

  vars_files:
    - vars/main.yml

  tasks:
  - name: Install pikaur manager
    aur:
        name: pikaur
        state: present

  - name: Install all packages
    aur:
        name: '{{ required_packages }}'
        state: present
        use: pikaur

  - name: Setup nsswitch.conf
    copy:
        src: files/nsswitch.conf
        dest: /etc/nsswitch.conf
        backup: yes
    become: yes
    notify: restart_avahi
    
  - name: Setup fonts
    blockinfile:
        path: /etc/fonts/local.conf
        block: |
            <?xml version="1.0"?>
            <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
            <fontconfig>
                <match>
                    <edit mode="prepend" name="family"><string>{{ sans_serif_font }}</string></edit>
                </match>
                <match target="pattern">
                    <test qual="any" name="family"><string>serif</string></test>
                    <edit name="family" mode="assign" binding="same"><string>{{ serif_font }}</string></edit>
                </match>
                <match target="pattern">
                    <test qual="any" name="family"><string>sans-serif</string></test>
                    <edit name="family" mode="assign" binding="same"><string>{{ sans_serif_font }}</string></edit>
                </match>
                <match target="pattern">
                    <test qual="any" name="family"><string>monospace</string></test>
                    <edit name="family" mode="assign" binding="same"><string>{{ monospace_font }}</string></edit>
                </match>
            </fontconfig>
        create: yes
    become: yes

  - name: Create bitmap symlinks
    file:
        src: "/etc/fonts/conf.avail/{{ item }}"
        dest: "/etc/fonts/conf.d/{{ item }}"
        state: link
    become: yes
    with_items:
        - 70-no-bitmaps.conf
        - 10-sub-pixel-rgb.conf
        - 11-lcdfilter-default.conf

  - name: Enable freetype properties
    replace:
      path: /etc/profile.d/freetype2.sh
      regexp: '^#(.*FREETYPE_PROPERTIES.*)'
      replace: '\1'
    become: yes

  - name: Enable systemd stuff
    systemd:
        name: '{{ item }}'
        state: started
        enabled: yes
    become: yes
    with_items: '{{ enabled_services }}'

  - name: User mods
    user:
        name: '{{ ansible_user_id }}'
        groups: docker
        append: yes
    become: yes

  - name: Auto connection for bluetooth
    blockinfile:
        path: /etc/pulse/default.pa
        block: |
            ### Automatically switch to newly-connected devices
            load-module module-switch-on-connect
    become: yes

  - name: Additional settings for bluetooth
    lineinfile:
        path: /etc/pulse/default.pa
        regexp: '^(.*load-module module-bluetooth-policy.*)$'
        backup: yes
        line: '\1 auto_switch=2'
    become: yes

  - name: Clone oh-my-zsh
    git:
      repo: https://github.com/ohmyzsh/ohmyzsh.git
      dest: "{{ ansible_user_dir }}/.oh-my-zsh"

  - name: Clone spaceship
    git:
      repo: https://github.com/denysdovhan/spaceship-prompt.git
      dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/spaceship-prompt"

  - name: Symlink spaceship theme
    file:
      src: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme" 
      dst: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/spaceship.zsh-theme"

  - name: Download dotfiles
    git:
        repo: '{{ dots_url }}'
        dest: '{{ ansible_user_dir }}/dotfiles'
        update: yes

  - name: Install dotfiles
    file:
        src: "{{ ansible_user_dir }}/dotfiles/{{ item.src }}"
        dest: "{{ ansible_user_dir }}/{{ item.dst }}"
        state: link
        force: yes
    with_items: '{{ dots_links }}'

  - name: Setup fonts
    shell: 'fc-cache -fv'

# HANDLERS
  handlers:
    - name: restart_avahi
      ansible.builtin.service:
        name: avahi-daemon
        state: restarted
      become: yes