---
- hosts: localhost
  become: no

  roles:
    - kewlfft.aur

  vars_files:
    - vars/main.yml

  tasks:
  - name: Install pikaur manager
    aur:
        name: pikaur
        state: present

  - name: Install all packages
    aur:
        name: '{{ required_packages }}'
        state: present
        use: pikaur

  - name: Setup nsswitch.conf
    copy:
        src: files/nsswitch.conf
        dest: /etc/nsswitch.conf
        backup: yes
    become: yes
    notify: restart_avahi
  
  - name: Setup local.conf for Fonts
    copy:
      src: files/local.conf
      dest: /etc/fonts/
    become: true

  - name: Create fontconfig symlinks
    file:
        src: "/usr/share/fontconfig/conf.avail/{{ item }}"
        dest: "/etc/fonts/conf.d/{{ item }}"
        state: link
    become: yes
    with_items:
        - 70-no-bitmaps.conf
        - 10-sub-pixel-rgb.conf
        - 11-lcdfilter-default.conf

  - name: Enable freetype properties
    replace:
      path: /etc/profile.d/freetype2.sh
      regexp: '^#(.*FREETYPE_PROPERTIES.*)'
      replace: '\1'
    become: yes

  - name: Enable systemd stuff
    systemd:
        name: '{{ item }}'
        state: started
        enabled: yes
    become: yes
    with_items: '{{ enabled_services }}'

  - name: User mods
    user:
        name: '{{ ansible_user_id }}'
        groups: docker
        append: yes
    become: yes

  - name: Auto connection for bluetooth
    copy:
      src: files/default.pa
      dest: /etc/pulse/default.pa
    become: true

  - name: Clone dependancies
    git:
      repo: '{{ item.repo }}'
      dest: '{{ item.dst }}'
    with_items: '{{ git_requirements }}'

  - name: Symlink spaceship theme
    file:
      src: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme" 
      dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
      state: link
      force: yes

  - name: Download dotfiles
    git:
        repo: '{{ dots_url }}'
        dest: '{{ ansible_user_dir }}/dotfiles'
        update: yes

  - name: Install dotfiles
    file:
        src: "{{ ansible_user_dir }}/dotfiles/{{ item.src }}"
        dest: "{{ ansible_user_dir }}/{{ item.dst }}"
        state: link
        force: yes
    with_items: '{{ dots_links }}'
    notify: refresh_fonts

# HANDLERS
  handlers:
    - name: restart_avahi
      ansible.builtin.service:
        name: avahi-daemon
        state: restarted
      become: yes

    - name: refresh_fonts
      shell: 'fc-cache -fv'