---
- hosts: localhost
  become: yes

  roles:
    - kewlfft.aur

  vars_files:
    - vars/main.yml

  tasks:
  - name: Install all required packages
    community.general.pacman:
        name: '{{ item }}'
        state: present
    with_items: '{{ required_packages }}'

  - name: Install AUR packages
    aur:
        name: '{{ item }}'
        state: present
    with_items: '{{ required_aur }}'
    become: no

  - name: Setup nsswitch.conf
    lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^myhostname$'
        line: '\1 mdns_minimal [NOTFOUND=return]'
        backup: yes
    notify: restart_avahi
    
  - name: Setup fonts
    blockinfile:
        path: /etc/fonts/local.conf
        block: |
            <?xml version="1.0"?>
            <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
            <fontconfig>
                <match>
                    <edit mode="prepend" name="family"><string>{{ sans_serif_font }}</string></edit>
                </match>
                <match target="pattern">
                    <test qual="any" name="family"><string>serif</string></test>
                    <edit name="family" mode="assign" binding="same"><string>{{ serif_font }}</string></edit>
                </match>
                <match target="pattern">
                    <test qual="any" name="family"><string>sans-serif</string></test>
                    <edit name="family" mode="assign" binding="same"><string>{{ sans_serif_font }}</string></edit>
                </match>
                <match target="pattern">
                    <test qual="any" name="family"><string>monospace</string></test>
                    <edit name="family" mode="assign" binding="same"><string>{{ monospace_font }}</string></edit>
                </match>
            </fontconfig>

  - name: Create bitmap symlinks
    file:
        src: '{{ item }}'
        dest: "/etc/fonts/conf.d"
        state: link
    with_items:
        - /etc/fonts/conf.avail/70-no-bitmaps.conf
        - /etc/fonts/conf.avail/10-sub-pixel-rgb.conf
        - /etc/fonts/conf.avail/11-lcdfilter-default.conf

  - name: Enable freetype properties
    replace:
      path: /etc/profile.d/freetype2.sh
      regexp: '^#(.*FREETYPE_PROPERTIES.*)'
      replace: '\1'

  - name: Enable systemd stuff
    service:
        name:
        state: enabled
    with_items: '{{ enabled_services }}'

  - name: User mods
    user:
        name: sean
        groups: docker
        append: yes